import { useEffect, useState, FormEvent } from 'react';
import { api } from '../api/client';
import type { Business, DiscoverResult, DiscoverStatus, Recommendation } from '../types';

const PLATFORM_EMOJI: Record<string, string> = {
  Reddit: '👽',
  Instagram: '📸',
  X: '🐦',
  TikTok: '🎵',
  YouTube: '▶️',
  Etsy: '🧡',
  Facebook: '👥',
  Pinterest: '📌',
  Discord: '🎮',
  Forum: '💬',
  Local: '📍',
  Other: '🌐',
};

const KIND_LABEL: Record<Recommendation['kind'], string> = {
  community: 'Community',
  hashtag: 'Hashtag',
  marketplace: 'Marketplace',
  search: 'Search recipe',
  event: 'Events',
};

export default function DiscoverTab({
  business,
  onBusinessUpdated,
  onFoundSomeone,
}: {
  business: Business;
  onBusinessUpdated: (b: Business) => void;
  onFoundSomeone: (communityUrl: string) => void;
}) {
  const [idealCustomer, setIdealCustomer] = useState(business.idealCustomer ?? '');
  const [keywords, setKeywords] = useState(business.audienceKeywords ?? '');
  const [editing, setEditing] = useState(!business.idealCustomer && !business.audienceKeywords);
  const [saving, setSaving] = useState(false);

  const [result, setResult] = useState<DiscoverResult | null>(null);
  const [status, setStatus] = useState<DiscoverStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = (refresh = false) => {
    setLoading(true);
    setError(null);
    api
      .getDiscover(business.id, refresh)
      .then(setResult)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    load();
    api.getDiscoverStatus().then(setStatus).catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [business.id]);

  const saveTargeting = async (e: FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      const updated = await api.updateBusiness(business.id, {
        idealCustomer: idealCustomer.trim(),
        audienceKeywords: keywords.trim(),
      });
      onBusinessUpdated(updated);
      setEditing(false);
      load(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div style={{ padding: 24, maxWidth: 820 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 8 }}>
        <div>
          <h2 style={{ marginBottom: 4 }}>Find your next customer 🔭</h2>
          <p style={{ color: 'var(--text-dim)', fontSize: 14, marginTop: 0 }}>
            Places where people who'd love {business.name} already hang out.
          </p>
        </div>
        {status && (
          <span
            className="channel-badge"
            title={status.llmConfigured ? `Recommendations generated by your model (${status.model})` : 'Using the built-in engine. Point LLM_BASE_URL in server/.env at your own model for tailored ideas.'}
          >
            {status.llmConfigured ? `🧠 Your AI · ${status.model}` : '⚙️ Starter engine'}
          </span>
        )}
      </div>

      {/* Targeting */}
      <section style={{ background: 'var(--panel)', border: '1px solid var(--panel-border)', borderRadius: 10, padding: 18, margin: '16px 0 24px' }}>
        {editing ? (
          <form onSubmit={saveTargeting}>
            <div className="field">
              <label htmlFor="ideal">Who's your ideal customer? Describe them like a friend.</label>
              <textarea
                id="ideal"
                value={idealCustomer}
                onChange={(e) => setIdealCustomer(e.target.value)}
                rows={2}
                placeholder='e.g. "Coffee lovers who care about handmade things and will pay more for something unique"'
              />
            </div>
            <div className="field">
              <label htmlFor="kw">Interests & keywords (comma-separated)</label>
              <input
                id="kw"
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
                placeholder="e.g. pottery, coffee, handmade gifts"
              />
            </div>
            <button className="btn" type="submit" disabled={saving}>
              {saving ? 'Saving…' : 'Save & get recommendations'}
            </button>
          </form>
        ) : (
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start' }}>
            <div style={{ fontSize: 14 }}>
              <div style={{ color: 'var(--text-dim)', fontSize: 12, marginBottom: 4 }}>You're looking for</div>
              {idealCustomer || <span style={{ color: 'var(--text-dim)' }}>anyone interested in {business.niche}</span>}
              {keywords && (
                <div style={{ marginTop: 8, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {keywords.split(',').map((k) => k.trim()).filter(Boolean).map((k) => (
                    <span key={k} className="chip" style={{ cursor: 'default' }}>{k}</span>
                  ))}
                </div>
              )}
            </div>
            <button className="btn-secondary" onClick={() => setEditing(true)} style={{ whiteSpace: 'nowrap' }}>
              Edit
            </button>
          </div>
        )}
      </section>

      {error && <p style={{ color: 'var(--danger)' }}>{error}</p>}
      {loading && !result && <p style={{ color: 'var(--text-dim)' }}>Scouting the internet for your people…</p>}

      {result && (() => {
        const communities = result.recommendations.filter((r) => r.kind !== 'search');
        const recipes = result.recommendations.filter((r) => r.kind === 'search');
        return (
          <>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
              <h3 style={{ margin: 0 }}>Find your customers here</h3>
              <button className="btn-secondary" onClick={() => load(true)} disabled={loading}>
                {loading ? 'Thinking…' : '↻ Fresh ideas'}
              </button>
            </div>
            <p style={{ color: 'var(--text-dim)', fontSize: 13, marginTop: 2, marginBottom: 12 }}>
              Big, active communities where your people already spend their time.
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 12 }}>
              {communities.map((rec) => <RecCard key={rec.url} rec={rec} onFoundSomeone={onFoundSomeone} />)}
            </div>

            {recipes.length > 0 && (
              <>
                <h3 style={{ marginTop: 28, marginBottom: 4 }}>Your search playbook</h3>
                <p style={{ color: 'var(--text-dim)', fontSize: 13, marginTop: 2, marginBottom: 12 }}>
                  Ready-made searches built from your own keywords — a different lens on every platform.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 12 }}>
                  {recipes.map((rec) => <RecCard key={rec.url} rec={rec} onFoundSomeone={onFoundSomeone} />)}
                </div>
              </>
            )}
          </>
        );
      })()}

      {result && result.source === 'builtin' && !status?.llmConfigured && (
        <p style={{ color: 'var(--text-dim)', fontSize: 12, marginTop: 20 }}>
          💡 These come from the built-in engine. Connect your own AI in My Business → Your AI for ideas
          tailored to your exact business.
        </p>
      )}
    </div>
  );
}

function RecCard({ rec, onFoundSomeone }: { rec: Recommendation; onFoundSomeone: (url: string) => void }) {
  return (
    <div
      style={{ background: 'var(--panel)', border: '1px solid var(--panel-border)', borderRadius: 12, padding: 16, display: 'flex', flexDirection: 'column', gap: 8 }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8 }}>
        <strong style={{ fontSize: 15 }}>
          {PLATFORM_EMOJI[rec.platform] ?? '🌐'} {rec.title}
        </strong>
        <span style={{ fontSize: 11, color: 'var(--text-dim)', border: '1px solid var(--panel-border)', borderRadius: 999, padding: '2px 8px', whiteSpace: 'nowrap' }}>
          {KIND_LABEL[rec.kind]}
        </span>
      </div>
      <p style={{ fontSize: 13, color: 'var(--text-dim)', margin: 0, flex: 1 }}>{rec.reason}</p>
      <div style={{ display: 'flex', gap: 8 }}>
        <a
          href={rec.url}
          target="_blank"
          rel="noreferrer"
          className="btn"
          style={{ textDecoration: 'none', fontSize: 13, padding: '6px 14px' }}
        >
          Explore ↗
        </a>
        <button
          className="btn-secondary"
          style={{ fontSize: 13, padding: '6px 14px' }}
          onClick={() => onFoundSomeone(rec.url)}
          title="Met someone promising here? Add them to your network."
        >
          Found someone 🎯
        </button>
      </div>
    </div>
  );
}
